AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
