#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup'

lib = File.expand_path('../lib', __dir__).freeze
$LOAD_PATH.unshift lib unless $LOAD_PATH.include? lib

require 'pry'

require 'main'

Main.instance
